# Generated by Django 3.2.9 on 2021-11-05 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Name')),
                ('creation_date', models.DateField(verbose_name='Creation date')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=50, verbose_name='Model')),
                ('color', models.CharField(choices=[('WHITE', 'White'), ('BLACK', 'Black'), ('GRAY', 'Gray'), ('BLUE', 'Blue'), ('RED', 'Red')], max_length=5, verbose_name='Color')),
                ('engine_type', models.CharField(choices=[('V6', 'V6'), ('V8', 'V8'), ('V12', 'V12')], max_length=4, verbose_name='Engine Type')),
                ('transmission_type', models.CharField(choices=[('M', 'Manual'), ('A', 'Automatic')], max_length=9, verbose_name='Transmission Type')),
                ('drivetrain_type', models.CharField(choices=[('AWD', 'All Wheel Drive'), ('FWD', 'Front Wheel Drive'), ('RWD', 'Rear Wheel Drive')], max_length=3, verbose_name='Drivetrain Type')),
                ('year', models.DateField(verbose_name='Manafacturing date')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.manufacturer')),
            ],
        ),
    ]
