# Generated by Django 3.2.9 on 2021-11-05 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='year',
            new_name='prod_date',
        ),
    ]
